### ISSUE TITLE
__TUPLE_NAMESPACE awareness

### ISSUE THREAD

**Issue by andrewcorrigan** [jaredhoberock/tuple_utility#2]
Would it make sense to check to see if __TUPLE_NAMESPACE [1] is defined, rather than assuming std?  

[1] https://github.com/jaredhoberock/tuple/blob/master/include/tuple#L19

**Comment by jaredhoberock** [comment]
I don't understand. The line of code you pointed at does check if `__TUPLE_NAMESPACE` is defined with an `#ifdef`.

**Comment by andrewcorrigan** [comment]
That line of code is in your tuple library. The question is referring to
tuple_utility. If I need to put your standalone tuple in another namespace,
I was hoping to still use tuple_utility with it.  As far as I can tell,
tuple_utility only appears to work with std::tuple at present.

**Comment by jaredhoberock** [comment]
The library in this repository is intended to work with any type at all which specializations for `std::tuple_element`, `std::tuple_size`, and an overload for `std::get`. It seems to work for my code.

**Comment by andrewcorrigan** [comment]
thanks for clarifying.  I had assumed that that `std::get` could only be used with `std::tuple`, etc.

**Comment by jaredhoberock** [comment]
The reason I built this tuple utility library was to manipulate types representing points in a multidimensional space. It's less useful if it can only handle `std::tuple`.
