### ISSUE TITLE
tuple_get

### ISSUE THREAD

**Issue by andrewcorrigan** [jaredhoberock/tuple_utility#9]
What do you think of `tuple_get`, a generalized form of `get`?  In general:
```
    tuple_get<I...>(tuple) == make_tuple(get<I>(tuple)...)
```
An example:
```
   auto a = make_tuple(1,2,3);
   assert(tuple_get<2,1>(a) == make_tuple(3,2));
   assert(tuple_get<0,0,1,1,2,2>(a) == make_tuple(1,1,2,2,3,3));
```
I could describe the specific application to illustrate how this would be extraordinarily useful, but suffice it to say, this would simplify a ton of code I have.  Would you be interested in such a contribution to your tuple_utility library?

**Comment by jaredhoberock** [comment]
Sounds good, but I would call it `tuple_gather`.

**Comment by andrewcorrigan** [comment]
Awesome.  I'll initiate a PR as soon as I can.

**Comment by andrewcorrigan** [comment]
The following appears to work:
```
template<typename T, size_t... I>
auto tuple_gather(T& t)
    -> std::tuple<typename std::tuple_element<I,T>::type&...>
{
    return std::tie(std::get<I>(t)...);
}

template<typename T, size_t... I>
auto tuple_gather(const T& t)
    -> std::tuple<typename std::tuple_element<I,T>::type...>
{
    return std::make_tuple(std::get<I>(t)...);
}
```
Since
```
  tuple_print(tuple_gather<decltype(t18),0,2>(t18));
  tuple_gather<decltype(t18),0,2>(t18) = std::make_tuple(12, "arithmetic");
  std::cout << std::endl;
  tuple_print(tuple_gather<decltype(t18),0,2>(t18));  
  std::cout << std::endl;
```
gives
```
13, not arithmetic
12, arithmetic
```
Ideally, we want `T` to be automatically deduced, and `I` to be explicitly specified.  Problem is that I think variadic template arguments must appear at the end, but explicit parameters need to appear at the beginning

Do you know of any workarounds?

**Comment by jaredhoberock** [comment]
Place the parameter pack before the `T` parameter. Since it is a non-type parameter pack, it should be deduceable:

``
#include <cstddef>
#include <tuple>
#include <cassert>

template<size_t... I, typename T>
auto tuple_gather(T& t)
    -> std::tuple<typename std::tuple_element<I,T>::type&...>
{
    return std::tie(std::get<I>(t)...);
}

template<size_t... I, typename T>
auto tuple_gather(const T& t)
    -> std::tuple<typename std::tuple_element<I,T>::type...>
{
    return std::make_tuple(std::get<I>(t)...);
}

int main()
{
  auto t = std::make_tuple(0,1,2,3,4);

  assert((tuple_gather<1,2,3>(t) == std::make_tuple(1,2,3)));
  assert((tuple_gather<0,1,3>(t) == std::make_tuple(0,1,3)));
  assert((tuple_gather<2,3,4>(t) == std::make_tuple(2,3,4)));
  assert((tuple_gather<4,1,2>(t) == std::make_tuple(4,1,2)));

  return 0;
}
```

**Comment by andrewcorrigan** [comment]
Thanks for clarifying.  I guess it does just work.  I could've sworn that in the past they had to be at the end.

Would an r-value reference overload also be required?    I don't understand r-value references very well, but it seems like moving the same tuple entry multiple times wouldn't make sense (the first time it's moved, it becomes invalid, right?). Although, maybe it would be ok if each element is only gathered once, and not multiple times?

**Comment by jaredhoberock** [comment]
I would implement two algorithms with these semantics:

```
template<size_t... I, typename Tuple, typename Function>
auto tuple_gather_invoke(Tuple&& t, Function f)
{
  return f(__get<I>(std::forward<Tuple>(t))...);
}

struct __maker
{
  template<class... Args>
  auto operator()(Args&&... args)
  {
    return make_tuple(std::forward<Args>(args)...);
  }
};

template<size_t... I, typename Tuple, typename Function>
auto tuple_gather(const Tuple& t)
{
  return tuple_gather_invoke(t, __maker());
}
```

`tuple_gather` would make a copy of the tuple's elements, so you don't need to worry about move semantics. If a client wants to move the elements, they can call `tuple_gather_invoke` with the appropriate function.

**Comment by andrewcorrigan** [comment]
Sorry for not replying immediately.  I said originally I would do a PR, and my intent was just to propose  `auto tuple_gather(T& t)` and `auto tuple_gather(const T& t)`.  But since you would prefer the more general `auto tuple_gather_invoke(Tuple&& t, Function f)`, I'll just hold off and please feel free to implement this the best way you see fit.

I would say, that I have found `tuple_gather` to be extremely expressive and concise in my own code, so I think it would be a great addition to your library.
